name: OpenWrt K2P DEV CI
on:
  watch:
    types: started
jobs:
  k2p:	
    runs-on: ubuntu-18.04	
    steps:	
    - name: 00 - clone repository	
      uses: actions/checkout@v1	
    - name: 01 - system build dependencies	
      run: sudo apt-get install subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc zip	
    - name: 02 - clone openwrt source
      run: |	
        git clone -b openwrt-19.07 https://git.openwrt.org/openwrt/openwrt.git
    - name: 03 - source update install	
      run: |	
        cd openwrt
        sed -i 's/-SNAPSHOT/.3/g' include/version.mk
        ./scripts/feeds update -a	
        ./scripts/feeds install -a	
    - name: 04 - remove shadowsocks plugin	
      run: |	
        cd openwrt
        rm -rf feeds/luci/applications/luci-app-shadowsocks-libev	
        rm -rf feeds/luci.tmp/info/.packageinfo-applications_luci-app-shadowsocks-libev	
        rm -rf feeds/packages/net/shadowsocks-libev	
        rm -rf feeds/packages.tmp/info/.packageinfo-net_shadowsocks-libev	
        rm -rf package/feeds/luci/luci-app-shadowsocks-libev	
        rm -rf package/feeds/packages/shadowsocks-libev	
    - name: 05 - openwrt plugin source	
      run: |	
        cd openwrt
        git clone https://github.com/LGA1150/openwrt-fullconenat.git package/fullconenat	
        git clone https://github.com/honwen/luci-app-aliddns.git package/luci-app-aliddns	
        git clone https://github.com/flytosky-f/openwrt-vlmcsd.git package/vlmcsd	
        git clone https://github.com/thisdk/openwrt-simple-obfs.git package/simple-obfs	
        git clone https://github.com/shadowsocks/openwrt-shadowsocks.git package/shadowsocks	
        git clone https://github.com/shadowsocks/luci-app-shadowsocks.git package/luci-app-shadowsocks	
        git clone https://github.com/zhfreal/openwrt-udp2raw.git package/udp2raw	
        git clone https://github.com/z826540272/openwrt-smartdns.git package/smartdns	
    - name: 06 - copy k2p build config	
      run: cp ./.config.19.07.03.k2p openwrt/.config	
    - name: 07 - openwrt build dependencies	
      run: |	
        cd openwrt	
        make download -j12	
    - name: 08 - make openwrt source	
      run: |	
        cd openwrt
        make -j6	
    - name: 09 - push to artifact file	
      uses: actions/upload-artifact@v1	
      with:	
        name: openwrt-k2p-build	
        path: openwrt-${{ env.VERSION }}/bin/	
