name: OpenWrt CI
on:
  release:
    types: [created]
jobs:
  k2p:	
    runs-on: ubuntu-18.04	
    env:	
      VERSION: 19.07.3	
      URL: https://github.com/openwrt/openwrt/archive/v19.07.3.tar.gz	
    steps:	
    - name: 00 - clone repository	
      uses: actions/checkout@v1	
    - name: 01 - system build dependencies	
      run: sudo apt-get install subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc zip	
    - name: 02 - openwrt source download	
      run: |	
        wget $URL	
        tar -zxf v$VERSION.tar.gz	
    - name: 03 - source update install	
      run: |	
        cd openwrt-$VERSION	
        ./scripts/feeds update -a	
        ./scripts/feeds install -a	
    - name: 04 - openwrt plugin source	
      run: |	
        cd openwrt-$VERSION	
        git clone https://github.com/LGA1150/openwrt-fullconenat.git package/fullconenat	
    - name: 05 - copy k2p build config	
      run: cp ./.config.19.07.03.k2p openwrt-$VERSION/.config	
    - name: 06 - openwrt build dependencies	
      run: |	
        cd openwrt-$VERSION	
        make download -j12	
    - name: 07 - make openwrt source	
      run: |	
        cd openwrt-$VERSION	
        make -j6	
    - name: 08 - push to artifact file	
      uses: actions/upload-artifact@v1	
      with:	
        name: openwrt-k2p-build	
        path: openwrt-${{ env.VERSION }}/bin/	
    - name: 09 - delete packages files	
      run: |	
        cd openwrt-$VERSION/bin/targets/ramips/mt7621/	
        rm -rf packages/
        ls -hl
    - name: 10 - push to release file	
      uses: softprops/action-gh-release@v1	
      if: startsWith(github.ref, 'refs/tags/')	
      with:	
        files: openwrt-${{ env.VERSION }}/bin/targets/ramips/mt7621/*	
      env:	
        GITHUB_TOKEN: ${{ secrets.RELEASES_DEPLOY_TOKEN }}
