name: OpenWrt K2P CI

on:
  release:
    types: [created]

jobs:

  none_job:
    runs-on: ubuntu-18.04
    env:
      VERSION: 19.07.3
      URL: https://github.com/openwrt/openwrt/archive/v19.07.3.tar.gz
    steps:
    - name: 00 - clone repository
      uses: actions/checkout@v1
    - name: 01 - system build dependencies
      run: sudo apt-get install subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc zip
    - name: 02 - openwrt source download
      run: |
        wget $URL
        tar -zxf v$VERSION.tar.gz
    - name: 03 - source update install
      run: |
        cd openwrt-$VERSION
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: 04 - remove shadowsocks plugin
      run: |
        cd openwrt-$VERSION
        rm -rf feeds/luci/applications/luci-app-shadowsocks-libev
        rm -rf feeds/luci.tmp/info/.packageinfo-applications_luci-app-shadowsocks-libev
        rm -rf feeds/packages/net/shadowsocks-libev
        rm -rf feeds/packages.tmp/info/.packageinfo-net_shadowsocks-libev
        rm -rf package/feeds/luci/luci-app-shadowsocks-libev
        rm -rf package/feeds/packages/shadowsocks-libev
    - name: 05 - openwrt plugin source
      run: |
        cd openwrt-$VERSION
        git clone https://github.com/LGA1150/openwrt-fullconenat.git package/fullconenat
        git clone https://github.com/honwen/luci-app-aliddns.git package/luci-app-aliddns
        git clone https://github.com/flytosky-f/openwrt-vlmcsd.git package/vlmcsd
        git clone https://github.com/thisdk/openwrt-simple-obfs.git package/simple-obfs
        git clone https://github.com/shadowsocks/openwrt-shadowsocks.git package/shadowsocks
        git clone https://github.com/zhfreal/openwrt-udp2raw.git package/udp2raw
        git clone https://github.com/jerrykuku/luci-theme-argon.git package/luci-theme-argon
        git clone https://github.com/z826540272/openwrt-smartdns.git package/smartdns
        git clone -b lede https://github.com/pymumu/luci-app-smartdns.git package/luci-app-smartdns
    - name: 06 - copy k2p build config
      run: cp ./.config.19.07.03.none openwrt-$VERSION/.config
    - name: 07 - openwrt build dependencies
      run: |
        cd openwrt-$VERSION
        make download -j12
    - name: 08 - make openwrt source
      run: |
        cd openwrt-$VERSION
        make -j6
    - name: 09 - push to artifact file
      uses: actions/upload-artifact@v1
      with:
        name: openwrt-k2p-build-none
        path: openwrt-${{ env.VERSION }}/bin/
    - name: 10 - delete packages files
      run: |
        cd openwrt-$VERSION/bin/targets/ramips/mt7621/
        rm -rf packages/
        for i in `ls`; do mv -f $i `echo "none."$i`; done
        ls -hl
    - name: 11 - push to release file
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: openwrt-${{ env.VERSION }}/bin/targets/ramips/mt7621/*
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASES_DEPLOY_TOKEN }}

  full_job:
    runs-on: ubuntu-18.04
    env:
      VERSION: 19.07.3
      URL: https://github.com/openwrt/openwrt/archive/v19.07.3.tar.gz
    steps:
    - name: 00 - clone repository
      uses: actions/checkout@v1
    - name: 01 - system build dependencies
      run: sudo apt-get install subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc zip
    - name: 02 - openwrt source download
      run: |
        wget $URL
        tar -zxf v$VERSION.tar.gz
    - name: 03 - source update install
      run: |
        cd openwrt-$VERSION
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: 04 - remove shadowsocks plugin
      run: |
        cd openwrt-$VERSION
        rm -rf feeds/luci/applications/luci-app-shadowsocks-libev
        rm -rf feeds/luci.tmp/info/.packageinfo-applications_luci-app-shadowsocks-libev
        rm -rf feeds/packages/net/shadowsocks-libev
        rm -rf feeds/packages.tmp/info/.packageinfo-net_shadowsocks-libev
        rm -rf package/feeds/luci/luci-app-shadowsocks-libev
        rm -rf package/feeds/packages/shadowsocks-libev
    - name: 05 - openwrt plugin source
      run: |
        cd openwrt-$VERSION
        git clone https://github.com/LGA1150/openwrt-fullconenat.git package/fullconenat
        git clone https://github.com/honwen/luci-app-aliddns.git package/luci-app-aliddns
        git clone https://github.com/flytosky-f/openwrt-vlmcsd.git package/vlmcsd
        git clone https://github.com/thisdk/openwrt-simple-obfs.git package/simple-obfs
        git clone https://github.com/shadowsocks/openwrt-shadowsocks.git package/shadowsocks
        git clone https://github.com/zhfreal/openwrt-udp2raw.git package/udp2raw
        git clone https://github.com/jerrykuku/luci-theme-argon.git package/luci-theme-argon
        git clone https://github.com/z826540272/openwrt-smartdns.git package/smartdns
        git clone -b lede https://github.com/pymumu/luci-app-smartdns.git package/luci-app-smartdns
    - name: 06 - copy k2p build config
      run: cp ./.config.19.07.03.full openwrt-$VERSION/.config
    - name: 07 - openwrt build dependencies
      run: |
        cd openwrt-$VERSION
        make download -j12
    - name: 08 - make openwrt source
      run: |
        cd openwrt-$VERSION
        make -j6
    - name: 09 - push to artifact file
      uses: actions/upload-artifact@v1
      with:
        name: openwrt-k2p-build-full
        path: openwrt-${{ env.VERSION }}/bin/
    - name: 10 - delete packages files
      run: |
        cd openwrt-$VERSION/bin/targets/ramips/mt7621/
        rm -rf packages/
        for i in `ls`; do mv -f $i `echo "full."$i`; done
        ls -hl
    - name: 11 - push to release file
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: openwrt-${{ env.VERSION }}/bin/targets/ramips/mt7621/*
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASES_DEPLOY_TOKEN }}

  mt7615e_job:
    runs-on: ubuntu-18.04
    env:
      VERSION: 19.07.3
      URL: https://github.com/openwrt/openwrt/archive/v19.07.3.tar.gz
    steps:
    - name: 00 - clone repository
      uses: actions/checkout@v1
    - name: 01 - system build dependencies
      run: sudo apt-get install subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc zip
    - name: 02 - openwrt source download
      run: |
        wget $URL
        tar -zxf v$VERSION.tar.gz
    - name: 03 - source update install
      run: |
        cd openwrt-$VERSION
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: 04 - remove shadowsocks plugin
      run: |
        cd openwrt-$VERSION
        rm -rf feeds/luci/applications/luci-app-shadowsocks-libev
        rm -rf feeds/luci.tmp/info/.packageinfo-applications_luci-app-shadowsocks-libev
        rm -rf feeds/packages/net/shadowsocks-libev
        rm -rf feeds/packages.tmp/info/.packageinfo-net_shadowsocks-libev
        rm -rf package/feeds/luci/luci-app-shadowsocks-libev
        rm -rf package/feeds/packages/shadowsocks-libev
    - name: 05 - openwrt plugin source
      run: |
        cd openwrt-$VERSION
        git clone https://github.com/LGA1150/openwrt-fullconenat.git package/fullconenat
        git clone https://github.com/honwen/luci-app-aliddns.git package/luci-app-aliddns
        git clone https://github.com/flytosky-f/openwrt-vlmcsd.git package/vlmcsd
        git clone https://github.com/thisdk/openwrt-simple-obfs.git package/simple-obfs
        git clone https://github.com/shadowsocks/openwrt-shadowsocks.git package/shadowsocks
        git clone https://github.com/zhfreal/openwrt-udp2raw.git package/udp2raw
        git clone https://github.com/jerrykuku/luci-theme-argon.git package/luci-theme-argon
        git clone https://github.com/z826540272/openwrt-smartdns.git package/smartdns
        git clone -b lede https://github.com/pymumu/luci-app-smartdns.git package/luci-app-smartdns
    - name: 06 - copy k2p build config
      run: cp ./.config.19.07.03.full.mt7615e openwrt-$VERSION/.config
    - name: 07 - openwrt build dependencies
      run: |
        cd openwrt-$VERSION
        make download -j12
    - name: 08 - make openwrt source
      run: |
        cd openwrt-$VERSION
        make -j6
    - name: 09 - push to artifact file
      uses: actions/upload-artifact@v1
      with:
        name: openwrt-k2p-build-full-mt7615e
        path: openwrt-${{ env.VERSION }}/bin/
    - name: 10 - delete packages files
      run: |
        cd openwrt-$VERSION/bin/targets/ramips/mt7621/
        rm -rf packages/
        for i in `ls`; do mv -f $i `echo "full.mt7615e."$i`; done
        ls -hl
    - name: 11 - push to release file
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: openwrt-${{ env.VERSION }}/bin/targets/ramips/mt7621/*
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASES_DEPLOY_TOKEN }}
