name: OpenWrt K2P DEV CI
on:
  watch:
    types: started
jobs:
  dev:	
    runs-on: ubuntu-20.04	
    steps:	
    - name: 01 - clone repository	
      uses: actions/checkout@v1	
    - name: 02 - system build dependencies	
      run: sudo apt-get install subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc zip
    - name: 03 - clone openwrt source
      run: git clone https://git.openwrt.org/openwrt/openwrt.git
    - name: 04 - configure & build
      run: bash script_dev.sh
    - name: 05 - push to artifact file	
      uses: actions/upload-artifact@v1	
      with:	
        name: k2p-dev-framework
        path: openwrt/bin/targets/ramips/mt7621/
