name: OpenWrt K2P DEV CI
on:
  schedule:
    - cron:  '0 8 * * *'
jobs:
  master:	
    runs-on: ubuntu-20.04	
    steps:	
    - name: 00 - clone repository	
      uses: actions/checkout@v1	
    - name: 01 - system build dependencies	
      run: sudo apt-get install subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc zip
    - name: 02 - clone openwrt source
      run: git clone https://git.openwrt.org/openwrt/openwrt.git
    - name: 04 - configure & build
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        git clone https://github.com/jerrykuku/luci-theme-argon.git package/luci-theme-argon
        git clone https://github.com/LGA1150/openwrt-fullconenat.git package/fullconenat
        git clone https://github.com/smzhzy/openwrt_vlmcsd.git package/vlmcsd
        cp ../.config.dev ./.config
        cp -r ../files ./
        make defconfig
        make download -j4
        make -j2
    - name: 05 - push to artifact file	
      uses: actions/upload-artifact@v1	
      with:	
        name: k2p-dev-framework
        path: openwrt/bin/targets/ramips/mt7621/
