name: OpenWrt Weekly CI
on:
  schedule:
    - cron:  '0 9 * * *'
jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      VERSION: 19.07.2
    steps:
    - name: 00 - clone repository
      uses: actions/checkout@v1
    - name: 01 - system build dependencies
      run: sudo apt-get install subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc zip
    - name: 02 - openwrt source download
      run: |
        git clone -b openwrt-19.07 https://git.openwrt.org/openwrt/openwrt.git openwrt-$VERSION
    - name: 03 - openwrt version replace
      run: |
        cd openwrt-$VERSION
        sed -i 's/-SNAPSHOT/.2/g' include/version.mk
    - name: 04 - source update install
      run: |
        cd openwrt-$VERSION
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: 05 - remove shadowsocks plugin
      run: |
        cd openwrt-$VERSION
        rm -rf feeds/luci/applications/luci-app-shadowsocks-libev
        rm -rf feeds/luci.tmp/info/.packageinfo-applications_luci-app-shadowsocks-libev
        rm -rf feeds/packages/net/shadowsocks-libev
        rm -rf feeds/packages.tmp/info/.packageinfo-net_shadowsocks-libev
        rm -rf package/feeds/luci/luci-app-shadowsocks-libev
        rm -rf package/feeds/packages/shadowsocks-libev
    - name: 06 - openwrt plugin source
      run: |
        cd openwrt-$VERSION
        git clone https://github.com/LGA1150/openwrt-fullconenat.git package/fullconenat
        git clone https://github.com/honwen/luci-app-aliddns.git package/luci-app-aliddns
        git clone https://github.com/flytosky-f/openwrt-vlmcsd.git package/vlmcsd
        git clone https://github.com/thisdk/openwrt-simple-obfs.git package/simple-obfs
        git clone https://github.com/shadowsocks/openwrt-shadowsocks.git package/shadowsocks
        git clone https://github.com/zhfreal/openwrt-udp2raw.git package/udp2raw
    - name: 07 - copy k2p build config
      run: cp ./.config.19.07.2.release openwrt-$VERSION/.config
    - name: 08 - openwrt build dependencies
      run: |
        cd openwrt-$VERSION
        make download -j12
    - name: 09 - make openwrt source
      run: |
        cd openwrt-$VERSION
        make -j6
    - name: 10 - delete packages files
      run: |
        cd openwrt-$VERSION/bin/targets/ramips/mt7621/
        rm -rf packages/
        ls -hl
    - name: 11 - push to artifact file
      uses: actions/upload-artifact@v1
      with:
        name: openwrt-k2p
        path: openwrt-${{ env.VERSION }}/bin/targets/ramips/mt7621/
